# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53e01b10142a32ab4a9eb965fc782f233961964e1af97ee46c556160016939218006d2d3105db054ce560e4c99167b6d5dfc8d7f0d9f457d1f8f2a70d8b57bcc

test:
  secret_key_base: 6f56448ccbf68c469d18709b6efe816a3e4a7040f322f0427a174c94a44311ce7a6337a977efd8ac1473381a5c509e520adbd497418e82643063522d9442d9b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
